version: "3.9"
services:
  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=roach1:26257
      - COCKROACH_INSECURE=true
      - COCKROACH_INIT=true
      - DATABASE_NAME=chirp_cockroach_dev
    depends_on:
      - roach1
      - roach2
      - roach3
  roach1:
    image: cockroachdb/cockroach:v22.1.6
    container_name: roach1
    hostname: roach1
    ports:
      - 8080:8080
      - 26257:26257
    volumes:
      - roach1:/cockroach/cockroach-data
    command: "start --insecure --join=roach1,roach2,roach3"
  roach2:
    image: cockroachdb/cockroach:v22.1.6
    container_name: roach2
    hostname: roach2
    volumes:
      - roach2:/cockroach/cockroach-data
    command: "start --insecure --join=roach1,roach2,roach3"
    depends_on:
      - roach1
  roach3:
    image: cockroachdb/cockroach:v22.1.6
    container_name: roach3
    hostname: roach3
    volumes:
      - roach3:/cockroach/cockroach-data
    command: "start --insecure --join=roach1,roach2,roach3"
    depends_on:
      - roach1
networks:
  default:
    name: roachnet
    external: true
volumes:
  roach1:
  roach2:
  roach3:



# remoember to docker network create -d bridge roachnet
# docker compose -f compose-cockroach.yml up
# add info about docker prune
