apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: roach2
  name: roach2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
